version: "3.9"
services:
  app:
    build: .
    container_name: supplier-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:supplierDB
      SPRING_DATASOURCE_USERNAME: chapur
      SPRING_DATASOURCE_PASSWORD: chapur
    ports:
      - "8080:8080"